### ISSUE TITLE
Undefined method Illuminate\Foundation\Application::share() when upgrading to Laravel 5.4

### ISSUE THREAD

**Issue by chinext** [ijeffro/laravel-airlines#2]
This error occur in v5.4, 

PHP Fatal error: Call to undefined method Illuminate\Foundation\Application::share() in vendor\ijeffro\laravel-airlines\src\jeffro\Airlines\Airlines ServiceProvider.php on line 72

i solved this by editing line 72
       // $this->app['command.airlines.migration'] = $this->app->share(function($app)
        $this->app->singleton('command.airlines.migration', function ($app)

**Comment by ijeffro** [comment]
Fixed

**Comment by ijeffro** [comment]
Fixed
